@startuml

skinparam monochrome true
top to bottom direction

:Spieler: as Player
:Streichholzschachtel: as Box

rectangle Nim-Spiel {
    (Auffüllen) as fillBox
    (Hölzchen ziehen) as drawMatch
    (Spielzug durchführen) as playTurn
    (Größe der Schachtel bestimmen) as setBox
    (Anzahl zurückgeben) as count
    (Gewinner zurückgeben) as win
}

Box -up-> fillBox
Box -up-> drawMatch
Box --> count
Player --> playTurn
Player --> setBox
Player --> win

setBox ..> fillBox
playTurn ..> drawMatch
playTurn ..> count
win ..> count

@enduml